os: linux
language: generic
sudo: required
services: docker
env:
  - RT_BRANCH=master
  - RT_BRANCH=releases

before_script:
    - git clone https://bitbucket.org/agriggio/art.git --branch $RT_BRANCH --single-branch --depth 1 art
    - cd art
    - bash ../check_commit.sh "continuous" ${RT_BRANCH} win64
    - 'if [ -e travis.cancel -a "$TRAVIS_EVENT_TYPE" = "cron" ]; then
        exit 0;
      fi'
script:
    - cd "$TRAVIS_BUILD_DIR"
    - bash win64/build.sh
after_success:
    - cd "$TRAVIS_BUILD_DIR"
    - ls -lhrt
    - ls -lhrt art
    - wget -c https://github.com/aferrero2707/uploadtool/raw/master/remove.sh
    - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
    - bash ./remove.sh "continuous" "ART_${RT_BRANCH}_" "_win64.zip" >& /dev/null;
    - bash  ./upload_rotate.sh "continuous" ${TRAVIS_BUILD_DIR}/art/ART_${RT_BRANCH}_*_win64.zip >& /dev/null;
    - bash  ./upload_rotate.sh "continuous" ${TRAVIS_BUILD_DIR}/art/commit-${RT_BRANCH}-win64.hash >& /dev/null

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    
